server:
  port: 9296

spring:
  application:
    name: CONFIGURATIONS-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SalemNabeelSalem/spring-cloud-config-microservice
          clone-on-start: true